const S={age:14,money:0,club:'Santos FC',level:'Sub-15',position:'Ponta',ovr:61,potential:84,followers:0,fame:4,reputation:45,titles:0,goals:0,assists:0,season:1,contract:0,partner:'Solteiro',children:0,house:'Casa da família',car:'Nenhum',career:'football',logs:[],events:0};
function updateCategory(notify=false){
  const previous=S.level;
  if(S.age<=15) S.level='Sub-15';
  else if(S.age<=17) S.level='Sub-17';
  else if(S.age<=20) S.level='Sub-20';
  else S.level='Profissional';
  if(notify && previous!==S.level){
    log(`📈 Você avançou de categoria: ${previous} → ${S.level}.`);
  }
}
const events=[
{title:'Convite para o Sub-17',text:'Seu treinador está impressionado com seu desempenho. Ele quer que você treine com uma categoria acima.',opts:[['Aceitar','Você encara o desafio e ganha experiência.','ovr',3],['Ficar na categoria atual','Você prefere jogar mais minutos e evoluir com calma.','reputation',3],['Conversar com o empresário','Você começa a pensar na carreira profissional.','fame',2]]},
{title:'Vídeo viral',text:'Um vídeo seu treinando viralizou nas redes sociais.',opts:[['Aproveitar a fama','Você começa a criar conteúdo sem abandonar o futebol.','followers',12000],['Ignorar e focar no futebol','Seu desempenho continua sendo prioridade.','ovr',2],['Fechar publicidade','Você consegue sua primeira renda com imagem.','money',800]]},
{title:'Olheiro europeu',text:'Um olheiro estrangeiro assistiu a uma partida e pediu informações sobre você.',opts:[['Aceitar contato','Seu nome começa a circular fora do Brasil.','fame',7],['Recusar por enquanto','Você quer se firmar primeiro no Santos.','reputation',4],['Pedir para falar com o clube','Você age com profissionalismo.','reputation',7]]},
{title:'Problema fora de campo',text:'Uma postagem sua gerou comentários negativos e pode afetar sua imagem.',opts:[['Pedir desculpas','Você assume a responsabilidade e recupera parte da reputação.','reputation',8],['Responder aos críticos','A discussão aumenta sua fama, mas prejudica sua reputação.','fame',8],['Não responder','O assunto perde força com o tempo.','reputation',2]]},
{title:'Convocação',text:'A comissão técnica da Seleção Brasileira quer acompanhar você de perto.',opts:[['Aceitar a oportunidade','Você entra no radar das categorias de base da Seleção.','fame',12],['Continuar focado no clube','Você prefere evitar distrações.','ovr',4],['Comemorar com a família','A notícia fortalece seu vínculo familiar.','reputation',5]]}
];
function money(){document.getElementById('money').textContent='R$ '+Number(S.money||0).toLocaleString('pt-BR')}function save(){try{if(window.localStorage){localStorage.setItem('v3',JSON.stringify(S));return true}}catch(e){}return false}function load(){try{if(window.localStorage){const raw=localStorage.getItem('v3');if(raw){const data=JSON.parse(raw);if(data&&typeof data==='object')Object.assign(S,data)}}}catch(e){}S.age=Number.isFinite(Number(S.age))?Number(S.age):14;S.money=Math.max(0,Number(S.money)||0);S.ovr=Math.max(1,Math.min(99,Number(S.ovr)||61));S.potential=Math.max(S.ovr,Math.min(99,Number(S.potential)||84));S.followers=Math.max(0,Number(S.followers)||0);S.fame=Math.max(0,Number(S.fame)||4);S.reputation=Math.max(0,Math.min(100,Number(S.reputation)||45));updateCategory(false);S.logs=Array.isArray(S.logs)?S.logs.slice(0,7):[];if(S.pending&&!S.pending.opts)S.pending=null}function log(x){S.logs.unshift('• '+x);S.logs=S.logs.slice(0,7);save()}
function show(x){let h='';if(x==='home')h=home();if(x==='career')h=career();if(x==='life')h=life();if(x==='news')h=news();document.getElementById('screen').innerHTML=h;money()}
function home(){return `<section class="card hero"><span class="tag">${S.age} anos</span><span class="tag">${S.club}</span><h1>${S.level} • ${S.position}</h1><p class="muted">Sua profissão não muda ao tocar em outros menus. Você constrói sua vida aos poucos.</p></section><section class="grid"><div class="stat"><span class="muted">OVR</span><b>${S.ovr}</b><div class="bar"><i style="width:${S.ovr}%"></i></div></div><div class="stat"><span class="muted">Potencial</span><b>${S.potential}</b><div class="bar"><i style="width:${S.potential}%"></i></div></div><div class="stat"><span class="muted">Fama</span><b>${S.fame}</b></div><div class="stat"><span class="muted">Seguidores</span><b>${S.followers.toLocaleString('pt-BR')}</b></div></section>${eventCard()}<section class="card"><h3>Próximo passo</h3><div class="actions"><button class="btn primary" onclick="advance()">⏩ Avançar 1 ano</button><button class="btn blue" onclick="randomEvent()">🎲 Acontecimento</button></div></section>`}
function career(){return `<section class="card"><h2>⚽ Minha carreira</h2><p><b>${S.club}</b> • ${S.level} • ${S.position}</p><p class="muted">Temporada ${S.season} • Categoria ${S.level} • Contrato ${S.contract?'profissional':'base'}</p></section><section class="grid"><div class="stat">🏆 Títulos <b>${S.titles}</b></div><div class="stat">⚽ Gols <b>${S.goals}</b></div><div class="stat">🎯 Assistências <b>${S.assists}</b></div><div class="stat">⭐ Reputação <b>${S.reputation}</b></div></section><section class="card"><h3>Ferramentas da carreira</h3><div class="actions"><button class="btn" onclick="train()">🏋️ Treinar</button><button class="btn" onclick="match()">🏟️ Jogar partida</button><button class="btn" onclick="transfer()">🔄 Mercado</button><button class="btn" onclick="contract()">💰 Contrato</button><button class="btn" onclick="selection()">🇧🇷 Seleção</button><button class="btn" onclick="idol()">👑 Legado</button></div></section><section class="card"><button class="btn danger" onclick="resetGame()">♻️ Reiniciar jogo</button><p class="muted" style="margin-top:8px">Use apenas se quiser apagar o progresso salvo neste navegador.</p></section>`}
function life(){return `<section class="card"><h2>❤️ Vida pessoal</h2><p>Relacionamento: <b>${S.partner}</b></p><p>Filhos: <b>${S.children}</b></p><p>Casa: <b>${S.house}</b></p><p>Carro: <b>${S.car}</b></p></section><section class="card"><h3>📱 Influenciador</h3><p class="muted">Sua carreira de influenciador é paralela ao futebol. Ela pode crescer sem substituir sua profissão.</p><button class="btn primary" onclick="content()">Criar conteúdo</button></section><section class="card"><h3>👨‍👩‍👧 Família e legado</h3><button class="btn" onclick="family()">Tomar decisão familiar</button></section>`}
function news(){return `<section class="card"><h2>📰 Notícias</h2>${S.logs.length?S.logs.map(x=>`<div class="log">${x}</div>`).join(''):'<p class="muted">Nenhuma notícia ainda. Os acontecimentos surgem conforme sua vida avança.</p>'}</section>`}
function eventCard(){if(!S.pending)return '';return `<section class="card event"><span class="tag">ACONTECIMENTO</span><h2>${S.pending.title}</h2><p>${S.pending.text}</p>${S.pending.opts.map((o,i)=>`<button class="btn choice" onclick="choose(${i})">${o[0]}<small>${o[2]==='ovr'?'+ evolução':o[2]==='money'?'+ dinheiro':o[2]==='followers'?'+ seguidores':o[2]==='fame'?'+ fama':'+ reputação'}</small></button>`).join('')}</section>`}
function randomEvent(){S.pending=events[Math.floor(Math.random()*events.length)];S.events++;show('home')}
function choose(i){let o=S.pending.opts[i],k=o[2],v=o[3];S[k]+=v;log(o[1]);if(k==='money')S.money=Math.max(0,S.money);S.pending=null;show('home')}
function advance(){const oldLevel=S.level;S.age++;S.season++;S.ovr=Math.min(99,S.ovr+(Math.random()<.7?1:0));updateCategory(false);if(S.age%2===0)S.money+=S.contract?50000:0;if(oldLevel!==S.level)log(`📈 Promoção de categoria: ${oldLevel} → ${S.level}.`);else log(`Você completou mais um ano de vida aos ${S.age} anos.`);if(Math.random()<.75)randomEvent();else show('home')}
function train(){S.ovr=Math.min(99,S.ovr+1);log('Treino intenso: sua evolução aumentou.');show('career')}function match(){let win=Math.random()<S.ovr/100;S.goals+=Math.random()<.35?1:0;S.assists+=Math.random()<.25?1:0;if(win){S.reputation+=3;if(Math.random()<.18)S.titles++;log('Grande atuação: você ganhou destaque na partida.')}else log('Partida difícil: você aprende com os erros.');show('career')}
function transfer(){let clubs=['Flamengo','Palmeiras','Corinthians','Real Madrid','Barcelona','Manchester City'];let c=clubs[Math.floor(Math.random()*clubs.length)];if(S.ovr>=70||S.age>=18){S.club=c;S.money+=S.ovr*1200;S.contract=1;log(`Transferência confirmada: ${c}. Sua carreira deu um novo passo.`)}else log('Ainda é cedo para uma grande transferência. Continue evoluindo.');show('career')}
function contract(){if(S.age<17){log('Você ainda está na base e não pode assinar um grande contrato profissional.')}else{S.contract=1;S.money+=Math.max(10000,S.ovr*1500);log('Você assinou um novo contrato profissional.') }show('career')}
function selection(){if(S.ovr>=75){S.fame+=15;log('🇧🇷 Você foi convocado para uma categoria da Seleção Brasileira!')}else log('A Seleção ainda não chamou. Seu desempenho precisa crescer.');show('career')}
function idol(){if(S.titles>=3&&S.fame>=50){S.reputation+=20;log('👑 Você começou a ser tratado como ídolo do clube.')}else log('Seu legado ainda está sendo construído.');show('career')}
function content(){S.followers+=Math.floor(Math.random()*5000)+1000;S.fame+=2;S.money+=Math.floor(S.followers/1000)*10;log('📱 Um conteúdo seu ganhou novos seguidores.');show('life')}function family(){if(S.age<18){log('Você ainda é jovem para esse tipo de decisão.')}else if(S.children>=3){log('Sua família já está completa nesta versão.')}else{S.children++;S.partner='Em relacionamento';log('Sua família cresceu e uma nova responsabilidade entrou na sua vida.')}show('life')}
function resetGame(){if(confirm('Apagar todo o progresso e começar novamente?')){try{localStorage.removeItem('v3')}catch(e){}location.reload()}}load();show('home');
